//This file defines constants used to easily construct characters on the VFD grids

#ifndef VFD_CHARS_H
#define VFD_CHARS_H

#define VFD_GRID0 (0x1 << 19)
#define VFD_GRID1 (0x1 << 18)
#define VFD_GRID2 (0x1 << 17)
#define VFD_GRID3 (0x1 << 16)
#define VFD_GRID4 (0x1 << 15)
#define VFD_GRID5 (0x1 << 14)
#define VFD_GRID6 (0x1 << 13)
#define VFD_GRID7 (0x1 << 12)
#define VFD_ALLGRIDS (VFD_GRID0 | VFD_GRID1 | VFD_GRID2 | VFD_GRID3 | VFD_GRID4 | VFD_GRID5 | VFD_GRID6 | VFD_GRID7)
#define VFD_GRIDS_LOW VFD_GRID7
#define VFD_GRIDS_HIGH VFD_GRID0


#define VFD_AN_SSEG_D (0x1 << 4)
#define VFD_AN_SSEG_E (0x1 << 5)
#define VFD_AN_SSEG_C (0x1 << 6)
#define VFD_AN_SSEG_G (0x1 << 7)
#define VFD_AN_SSEG_F (0x1 << 8)
#define VFD_AN_SSEG_B (0x1 << 9)
#define VFD_AN_SSEG_A (0x1 << 10)
#define VFD_AN_SSEG_ALL (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)


#define VFD_AN_TOPIND (0x1 << 11) //top incidators (BAKE, TIMER, etc. Changes per grid)
#define VFD_AN_BOTIND (0x1 << 1) //bottom indicators (DRY, CLEAN, etc. Changes per grid)

#define VFD_AN_BOTCOLON (0x1 << 0)
#define VFD_AN_TOPCOLON (0x1 << 11)

#define VFD_BLANK 0x00000000
#define VFD_A (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_B ( VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_C (VFD_AN_SSEG_A | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F)
#define VFD_D (VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_G)
#define VFD_E (VFD_AN_SSEG_A | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_F (VFD_AN_SSEG_A | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_G (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_H (VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_I (VFD_AN_SSEG_E | VFD_AN_SSEG_F )
#define VFD_J (VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E )
#define VFD_L (VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F )
#define VFD_N (VFD_AN_SSEG_C | VFD_AN_SSEG_E | VFD_AN_SSEG_G)
#define VFD_O (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_F | VFD_AN_SSEG_E |VFD_AN_SSEG_C | VFD_AN_SSEG_D)
#define VFD_P (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_Q (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_R (VFD_AN_SSEG_E | VFD_AN_SSEG_G)
#define VFD_S (VFD_AN_SSEG_A | VFD_AN_SSEG_F | VFD_AN_SSEG_G | VFD_AN_SSEG_C | VFD_AN_SSEG_D)
#define VFD_T (VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_U (VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F )
#define VFD_Y (VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_F | VFD_AN_SSEG_G)

#define VFD_0 (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F )
#define VFD_1 (VFD_AN_SSEG_B | VFD_AN_SSEG_C )
#define VFD_2 (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_G)
#define VFD_3 (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_G)
#define VFD_4 (VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_5 (VFD_AN_SSEG_A | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_6 (VFD_AN_SSEG_A | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_7 (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C )
#define VFD_8 (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_E | VFD_AN_SSEG_F | VFD_AN_SSEG_G)
#define VFD_9 (VFD_AN_SSEG_A | VFD_AN_SSEG_B | VFD_AN_SSEG_C | VFD_AN_SSEG_D | VFD_AN_SSEG_F | VFD_AN_SSEG_G)

#endif

